### ISSUE TITLE
samtools image not found. Abort trap 6

### ISSUE THREAD

**Issue by Jothivanan-Elumalai** [samtools/samtools#974]
I am using  samtools 1.7-1 under anaconda on Mac OS High Sierra. I have not changed anything recently but suddenly samtools is not executing. It shows the below error on command line when samtools is executed in terminal.

Last login: Thu Nov  1 16:05:42 on ttys000
dhcp12-181:~ jothivananelumalai$ samtools
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /anaconda2/bin/samtools
  Reason: image not found
Abort trap: 6
dhcp12-181:~ jothivananelumalai$ 

Can someone help me with this issue?

**Comment by jkbonfield** [comment]
This sounds like an anaconda issue, or something on your system has changed.  It's not a samtools problem.

The message implies the libcrypto library is no longer installed.  Perhaps manually reinstalling it again will cure the problem.

**Comment by Jothivanan-Elumalai** [comment]
Yes, You are right. It was the problem with the libcrypto library. Just figured it out. 

Thank you.

**Comment by sebweyn** [comment]
I had the same issue in Mojave, which was fixed using the symlinks here: https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7

**Comment by Jothivanan-Elumalai** [comment]
> I had the same issue in Mojave, which was fixed using the symlinks here: https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7

Thank you. I did the same to solve the issue. Actually, it was not the problem with samtools but with library files.

**Comment by coffee-and-genomics** [comment]
The way I solved this issue was:

1. `conda uninstall samtools`
2. `conda update --all`
3. `conda install samtools`

**Comment by shahramsaghaei** [comment]
If you are using a conda env, simply use 

    conda install -c bioconda samtools openssl=1.0

**Comment by jmarshall** [comment]
> `conda install -c bioconda samtools openssl=1.0`

It you do this, you'll currently end up with samtools 1.3.1 from almost five years ago — as you are asking for a samtools compatible with a long-since outdated version of openssl. Conda samtools had openssl-related problems in the past, but they have been resolved for many months. Conda samtools has also had libdeflate-related problems, but these have been resolved since mid January.

So since January you should just use

```
conda install -c bioconda samtools
```

(or really just `conda install samtools` if your [channels are set up correctly](https://bioconda.github.io/user/install.html#set-up-channels)) which will give you the latest version, currently 1.12.

**Comment by shahramsaghaei** [comment]
Thanks for reply, but unfortunately, `conda install -c bioconda samtools` does not solve my issue. It raise this error:

> dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
> Referenced from: /Users/you/miniconda3/envs/Sam/bin/samtools
> Reason: image not found
> zsh: abort      samtools

Accordingly, I created a new environment, then using `conda install -c bioconda samtools openssl=1.0` the problem solved for me. 

I use macOS Big Sur, ver 11.1 (20C69), zsh and miniconda. I guess this command works for Linux OS, because 'pb-assembly' is not available in [PacBio tools ](https://github.com/PacificBiosciences/pbbioconda) anymore.
Just to give a more clear detail, here is the list of packages installed on the environment that I ran `conda install -c bioconda samtools` command for install the samtools. But I received the above error for samtools execution. 

# packages in environment at /Users/you/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
argparse                  1.4.0                    py36_0    bioconda
bedtools                  2.29.2               h37cfd92_0    bioconda
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.11.0                        0    bioconda
ca-certificates           2020.12.5            h033912b_0    conda-forge
cairo                     1.16.0            h4ec454a_1007    conda-forge
certifi                   2020.12.5        py36h79c6626_1    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py36h7b4949f_1    conda-forge
dask-core                 2020.12.0          pyhd8ed1ab_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
ffmpeg                    4.3.1                he496704_1    conda-forge
fontconfig                2.13.1            h07ff6b0_1003    conda-forge
freetype                  2.10.4               h3f75d11_0    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
glib                      2.66.4               h22858aa_1    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.6.13               h756fd2b_1    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
harfbuzz                  2.7.2                hf28d55f_2    conda-forge
hdf5                      1.10.6          nompi_h0f9794f_1112    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
jasper                    1.900.1           h636a363_1006    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
kiwisolver                1.3.1            py36he46ecad_0    conda-forge
kneed                     0.7.0              pyh9f0ad1d_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lame                      3.100             h1de35cc_1001    conda-forge
lcms2                     2.11                 h11f7e16_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h4c3b8ed_1    conda-forge
libdeflate                1.0                  h1de35cc_1    bioconda
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0               h6c81a4c_15    conda-forge
libgfortran5              9.3.0               h6c81a4c_15    conda-forge
libglib                   2.66.4               h7424822_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
liblapacke                3.9.0                3_openblas    conda-forge
libnghttp2                1.41.0               h8a08a2b_1    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libopencv                 4.5.0                    py36_3    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libuuid                   2.32.1            h35c211d_1000    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
matplotlib                3.3.3            py36h79c6626_0    conda-forge
matplotlib-base           3.3.3            py36h50af36e_0    conda-forge
mysql-connector-c         6.1.11            h0f02589_1007    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nettle                    3.6                  hedd7734_0    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.4           py36h08dc641_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                hd174df1_0    conda-forge
openssl                   1.1.1j               hbcf498f_0    conda-forge
pandas                    1.1.5            py36h2be6da3_0    conda-forge
pathlib                   1.0.1            py36h9f0ad1d_3    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pillow                    8.0.1            py36hc86fed5_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
py-opencv                 4.5.0            py36h9cf137f_3    conda-forge
pybedtools                0.8.1            py36h0c56d2d_2    bioconda
pybigwig                  0.3.17           py36h8c929e3_2    bioconda
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.15.3           py36h726f235_1    bioconda
python                    3.6.12          h6c3b2c9_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py36h809c706_3    conda-forge
pyyaml                    5.3.1            py36ha3de816_1    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
samtools                  1.4.1                         0    bioconda
scikit-image              0.16.2           py36h4f17bb1_0    conda-forge
scikit-learn              0.24.0           py36hed11f80_0    conda-forge
scipy                     1.5.3            py36h04de62b_0    conda-forge
setuptools                49.6.0           py36h2432673_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
statsmodels               0.12.1           py36hb29be1e_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py36h6941dd6_0    conda-forge
ucsc-bedgraphtobigwig     377                  h516baf0_1    bioconda
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
x264                      1!152.20180806       h1de35cc_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge

**Comment by jmarshall** [comment]
Your test environment has a really old version of libdeflate, which is probably what has drawn the solver towards an ancient samtools build that does not work with the openssl in that environment.

You are correct that installing into a fresh environment is the easiest way to resolve these problems. So the full advice is to use `conda install -c bioconda samtools` **in a new environment**. Or to create a new environment and install in one step, with `conda create -n samtoolsenv -c bioconda samtools`.

> Accordingly, I created a new environment, then using `conda install -c bioconda samtools openssl=1.0` the problem solved for me.

If you check what version of samtools is in your new environment, you will find that it is an old one. This is probably not what most people want.

**Comment by shahramsaghaei** [comment]
> Your test environment has a really old version of libdeflate, which is probably what has drawn the solver towards an ancient samtools build that does not work with the openssl in that environment.
> 
> You are correct that installing into a fresh environment is the easiest way to resolve these problems. So the full advice is to use `conda install -c bioconda samtools` **in a new environment**. Or to create a new environment and install in one step, with `conda create -n samtoolsenv -c bioconda samtools`.
> 
> > Accordingly, I created a new environment, then using `conda install -c bioconda samtools openssl=1.0` the problem solved for me.
> 
> If you check what version of samtools is in your new environment, you will find that it is an old one. This is probably not what most people want.

Maybe my problem is not a general issue, but I did exactly you suggest as following:

 > conda create -n samtoolsenv -c bioconda samtools
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/you/miniconda3/envs/samtoolsenv

  added / updated specs:
    - samtools


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    htslib-1.12                |       h422799e_0         1.9 MB  bioconda
    samtools-1.12              |       h5d3c5f0_0         386 KB  bioconda
    ------------------------------------------------------------
                                           Total:         2.3 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-hc929b4f_4
  c-ares             conda-forge/osx-64::c-ares-1.17.1-h0d85af4_1
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  htslib             bioconda/osx-64::htslib-1.12-h422799e_0
  krb5               conda-forge/osx-64::krb5-1.17.2-h60d9502_0
  libcurl            conda-forge/osx-64::libcurl-7.75.0-h8ef9fac_0
  libcxx             conda-forge/osx-64::libcxx-11.1.0-habf9029_0
  libdeflate         conda-forge/osx-64::libdeflate-1.7-h35c211d_5
  libedit            conda-forge/osx-64::libedit-3.1.20191231-h0678c8f_2
  libev              conda-forge/osx-64::libev-4.33-haf1e3a3_1
  libnghttp2         conda-forge/osx-64::libnghttp2-1.43.0-h07e645a_0
  libssh2            conda-forge/osx-64::libssh2-1.9.0-h52ee1ee_6
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  openssl            conda-forge/osx-64::openssl-1.1.1j-hbcf498f_0
  samtools           bioconda/osx-64::samtools-1.12-h5d3c5f0_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010


Proceed ([y]/n)? y


Downloading and Extracting Packages
htslib-1.12          | 1.9 MB    | ###################################################### | 100% 
samtools-1.12        | 386 KB    | ###################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate samtoolsenv
#
# To deactivate an active environment, use
#
#     $ conda deactivate

> (samtoolsenv)  ~/Desktop/testfolder/Hela > samtools
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/shahramsaghaei/miniconda3/bin/samtools
  Reason: image not found
zsh: abort      samtools

Is there any other suggestion for my issue, please?

**Comment by jmarshall** [comment]
> (**samtoolsenv**) ~/Desktop/testfolder/Hela > samtools
> dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
> Referenced from: /Users/shahramsaghaei/**miniconda3/bin**/samtools

You have activated your new `samtoolsenv` environment successfully, but the `samtools` executable you are running is from your `base` environment. This is a problem local to your machine: you need to clean out your `$PATH` environment variable, and it's probably a bad idea to install scientific tools into your base environment.

**Comment by shahramsaghaei** [comment]
I'm not sure this is correct. This is not the case for this problem. Actually it is not the `base`, 

>(samtoolsenv)  ~ > echo $PATH
/Users/you/miniconda3/envs/samtoolsenv/bin:/Users/you/miniconda3/bin:/Users/you/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

>(samtoolsenv)  ~/Desktop/you/testFolder/Hela > samtools
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/you/miniconda3/bin/samtools
  Reason: image not found
zsh: abort      samtools

**Comment by jkbonfield** [comment]
It may have remembered the old binary location.  In bash you can use `hash -r` to remove any cached binary location, or obviously specify the full pathname to be sure.

**Comment by jmarshall** [comment]
The message you got (“_Referenced from: /Users/you/miniconda3/bin/samtools_”) indicates that the `samtools` you have run is from the base environment. (Normally that directory would no longer be in your path at all after `conda activate samtoolsenv`…) You should check into:

* What running it via the full path `/Users/you/miniconda3/envs/samtoolsenv/bin/samtools --version` produces, and what version of samtools it says it is
* What `/Users/you/miniconda3/bin/samtools` produces
* Use `hash -r` (this clears the cache in zsh too), but this should have been taken care of by the $PATH manipulations inside `conda activate` (and it was for me on Mojave with zsh)
* Whether `conda list -n samtoolsenv` does indeed show that any samtools package is installed in this environment
* Whether `conda list -n base` shows any samtools package installed in the base environment
* Try doing all this in a fresh terminal window too (to really avoid any cache issues)

This problem appears to be local to your machine and is of decreasing interest to the original people on this issue. If you want further help with your conda setup, I suggest taking this to [biostars](https://www.biostars.org) or [bioinf.SE](https://bioinformatics.stackexchange.com) where more conda experts will be available to help.
